Repository DontShaveTheYak/cf2tf, pull requests merged in 2023-07, with the labels that each got.

#188 change search algorithm to get better search results
  src/cf2tf/terraform/code.py
  tests/test_terraform/test_code.py
Labels: enhancement, minor

#190 Fix bug when parsing attributes that are nested
  src/cf2tf/app.py
  src/cf2tf/terraform/doc_file.py
Labels: bug, patch

#191 fix automatic tag conversion error when tags are already a map
  src/cf2tf/conversion/overrides.py
Labels: bug, patch

#192 fix bug where a ref would fail if the resource had no attributes
  src/cf2tf/conversion/expressions.py
Labels: bug, patch

#193 allow select to be nested inside of equals
  src/cf2tf/conversion/expressions.py
Labels: chore, patch

#195 add better error handling when solving intrinsic functions
  src/cf2tf/convert.py
Labels: enhancement, patch

#205 Update the attributes section
  src/cf2tf/terraform/doc_file.py
Labels: bug, patch
