Repository DontShaveTheYak/cf2tf, pull requests merged in 2023-11, with the labels that each got.

#229 Make parsing Attributes from Terraform documentation more robust
  src/cf2tf/terraform/doc_file.py
  tests/test_convert.py
  tests/test_terraform/test_code.py
Labels: bug, patch

#225 docs: add homebrew installation note
  README.md
Labels: chore, patch

#233 add boolean type
  src/cf2tf/convert.py
  src/cf2tf/terraform/hcl2/primitive.py
  tests/test_terraform/test_configuration.py
Labels: enhancement, minor

#235 Add support for python 3.12
  .devcontainer/Dockerfile
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .python-version
  README.md
  noxfile.py
  src/cf2tf/save.py
  src/cf2tf/terraform/hcl2/primitive.py
Labels: chore, patch

#232 fix test arg path in vscode debug config
  .vscode/launch.json
Labels: chore, patch

#237 fix "Condition" key being treated like a intrinsic function
  src/cf2tf/cloudformation/_template.py
  src/cf2tf/convert.py
  src/cf2tf/terraform/hcl2/primitive.py
  tests/data/templates/04_cluster_bootstrap.yaml
  tests/data/templates/05_cluster_master_nodes.yaml
  tests/data/templates/aws-ecr-continuouscompliance-v1.yaml
  tests/data/templates/aws-instance-scheduler.template
  tests/data/templates/aws-trusted-advisor-explorer.template
  tests/data/templates/cloudtrail.yaml.txt
  tests/data/templates/crawler-cfn.yml
  tests/data/templates/debug.yaml
  tests/data/templates/depopry.yaml
  tests/data/templates/iam.yaml
  tests/data/templates/instance_state.yaml
  tests/data/templates/latest.yaml
  tests/data/templates/live-streaming-on-aws.template
  tests/data/templates/minecraft.yml
  tests/data/templates/platform-aurora-cluster.cf.txt
  tests/test_functional/test_conversion.py
Labels: bug, patch

#238 Allow cidr function to be nested inside of select function
  src/cf2tf/conversion/expressions.py
  tests/data/templates/conversions-api-gateway.eks_multiaccount_dual_nat.yaml
Labels: bug, patch
